### ISSUE TITLE
existing environment.yaml file fails with errors

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/pydelmod#3]
Creating the pydelmod environment from yaml file failed. 
Created using script and that worked and created a working environment with all the packages.
@kjnam Should we do this instead of the create from environment. See script below to execute

> conda create -y -n pydelmod
conda install -y python=3.7.*
conda install -c defaults -c cadwr-dms pyhecdss
conda install -y -n pydelmod -c defaults -c plotly plotly=3.*
conda install -y -n pydelmod -c defaults scipy jupyter matplotlib shapely xarray
conda install -y -n pydelmod -c defaults gdal holoviews
conda install -y -n pydelmod -c defaults -c conda-forge jupyter_contrib_nbextensions

**Comment by kjnam** [comment]
The issue can be reproduced. It seems like a sort of a channel clash. Looking into the issue.

**Comment by kjnam** [comment]
The environment yaml is updated. It uses Pandas v0.25, and it will be updated with Pandas v1.
